[project]
name = "tarsq"
version = "0.1.16"
description = "A fast, production-ready task queue for Python"
authors = [
    {name = "Preqsy",email = "obbyprecious24@gmail.com"}
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

dependencies = [
    "redis>=4.0.0",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "parsedatetime (>=2.6,<3.0)",
    "recurrent (>=0.4.1,<0.5.0)",
    "croniter (>=6.2.2,<7.0.0)"
]

[project.urls]
Homepage = "https://github.com/preqsy/tarsq"
Repository = "https://github.com/preqsy/tarsq"


[project.scripts]
tarsq = "tarsq.cli:start"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)",
    "psutil (>=7.2.2,<8.0.0)"
]
